version: "3"

services:
  database:
    image: "postgres:13-alpine"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "test-task-db"
    ports:
      - "5432:5432"
